global:
  app:
    port: 3000
    urlBase: /mdbbs
    name: MDBBS
    author: Ituki Kirihara/NI
  session:
    secret: 'I(H&@*ikotyu)'
    type: 'file-store' # 'file-store' or 'redis'
    maxAge: 604800 # in seconds # 7days 
  cache:
    type: 'memory' # 'memory' or 'redis'
  database:
    type: 'postgres'

  postgres:
    client: 'pg'
    connection:
      host: '127.0.0.1'
      port: 5432
      database: 'postgres_dev'
      user: 'postgres'
      password: 'postgres'
      requestTimeout: 2000
    pool:
      min: 10
      max: 50
    migrations:
      directory: '../migrations'
      tableName: 'knex_migrations'

  redis:
    host: '127.0.0.1'
    port: 6379
    db: 1
    password: ''
    prefix: 'dev'

  memory:
    max: 1000
    ttl: 3600

  s3:
    client:
      bucket: 'dev'
      region: ''
      endpoint: 'http://127.0.0.1:4568'
      credentials:
        accessKeyId: 'my-access-key-id'
        secretAccessKey: 'my-secret-access-key'
    server:
      enabled: true
      port: 4568
      address: '127.0.0.1'
      serviceEndpoint: 'http://127.0.0.1:4568'
      silent: false
      directory: './data/s3/'
  
  sessionFileStore:
    directory: './data/sessions/'

  logger:
    level: 'debug'
    transports:
      - type: 'console'
      - type: 'file'
        filename: 'development.log'
        maxSize: '10m'
        maxFiles: 5

  pageConfig:
    thread:
      view:
        listmax: 20
        lastmax: 5
        perpage: 10
        pageindex: 5
        treemax: 2

Modules:
  UserManager:
    HASHING_SUGAR_KEY: 08uytrecdftvgnhujimiuhytrcdfimjok
    HASHING_PEPPER_KEY: iH&h8ukijy7g6t8u90o
    BCRYPT_SALT_ROUNDS: 12
    passwordCheck:
      lockout:
        count: 10
        second: 10
      unknown_user:
        hash_size: 10
        rand_unlock: 0.05
